config/routes.rb
Rails.application.routes.draw do
  resources :presupuesto_detalles
  resources :presupuestos
  resources :categorias
  resources :usuarios
  resources :usuarios
  resources :usuarios
  resources :productos

  root 'categorias#index'

end

app/models/presupuesto.rb
class Presupuesto < ActiveRecord::Base
end

app/controllers/presupuestos_controller.rb
class PresupuestosController < ApplicationController
  before_action :set_presupuesto, only: [:show, :edit, :update, :destroy]

  # GET /presupuestos
  # GET /presupuestos.json
  def index
    @presupuestos = Presupuesto.all
  end

  # GET /presupuestos/1
  # GET /presupuestos/1.json
  def show
  end

  # GET /presupuestos/new
  def new
    @presupuesto = Presupuesto.new
  end

  # GET /presupuestos/1/edit
  def edit
  end

  # POST /presupuestos
  # POST /presupuestos.json
  def create
    @presupuesto = Presupuesto.new(presupuesto_params)

    respond_to do |format|
      if @presupuesto.save
        format.html { redirect_to @presupuesto, notice: 'Presupuesto was successfully created.' }
        format.json { render :show, status: :created, location: @presupuesto }
      else
        format.html { render :new }
        format.json { render json: @presupuesto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presupuestos/1
  # PATCH/PUT /presupuestos/1.json
  def update
    respond_to do |format|
      if @presupuesto.update(presupuesto_params)
        format.html { redirect_to @presupuesto, notice: 'Presupuesto was successfully updated.' }
        format.json { render :show, status: :ok, location: @presupuesto }
      else
        format.html { render :edit }
        format.json { render json: @presupuesto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presupuestos/1
  # DELETE /presupuestos/1.json
  def destroy
    @presupuesto.destroy
    respond_to do |format|
      format.html { redirect_to presupuestos_url, notice: 'Presupuesto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presupuesto
      @presupuesto = Presupuesto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presupuesto_params
      params.require(:presupuesto).permit(:fecha)
    end
end

app/helpers/presupuestos_helper.rb
module PresupuestosHelper
end

app/views/presupuestos/_form.html.erb
<%= form_for(@presupuesto) do |f| %>
  <% if @presupuesto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@presupuesto.errors.count, "error") %> prohibited this presupuesto from being saved:</h2>

      <ul>
      <% @presupuesto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.text_field :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/presupuestos/edit.html.erb
<h1>Editing Presupuesto</h1>

<%= render 'form' %>

<%= link_to 'Show', @presupuesto %> |
<%= link_to 'Back', presupuestos_path %>

app/views/presupuestos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Presupuestos</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presupuestos.each do |presupuesto| %>
      <tr>
        <td><%= presupuesto.fecha %></td>
        <td><%= link_to 'Show', presupuesto %></td>
        <td><%= link_to 'Edit', edit_presupuesto_path(presupuesto) %></td>
        <td><%= link_to 'Destroy', presupuesto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Presupuesto', new_presupuesto_path %>

app/views/presupuestos/new.html.erb
<h1>New Presupuesto</h1>

<%= render 'form' %>

<%= link_to 'Back', presupuestos_path %>

app/views/presupuestos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @presupuesto.fecha %>
</p>

<%= link_to 'Edit', edit_presupuesto_path(@presupuesto) %> |
<%= link_to 'Back', presupuestos_path %>